# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Pack
        run: |
          echo Building FileBuster contained binary
          sudo apt update
          sudo apt install cpanminus build-essential libperl-dev libssl-dev
          sudo cpan install -T PAR::Packer YAML Furl Benchmark Net::DNS::Lite List::MoreUtils IO::Socket::SSL URI::Escape HTML::Entities IO::Socket::Socks::Wrapper URI::URL Cache::LRU IO::Async::Timer::Periodic IO::Async::Loop Net::SSLeay
          pp -o filebuster -l libssl.so.1.0.0 -l libcrypto.so.1.0.0 -M "IO::Async::Loop::**" -M "Metrics::Any::Adapter::**" -M "IO::Async::Internals::**" filebuster.pl
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: filebuster
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
